# site
title: Itchyeggie
baseurl: "/archive"
url: "https://beckenkaru.github.io"
favicon: "/assets/ico.png"
g_analytics: UA-12345678-1

# bio
header: ÄGGIE'S
desc: >
  Upcoming and Commissioned work, sketch archive, prints, animations. \\ <a href=" https://beckenkaru.github.io/2020/12/16/about">About</a>.

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
