# site
title: Itchyeggie
baseurl: "/archive"
url: "https://beckenkaru.github.io"
favicon: "/assets/ico.png"
g_analytics: UA-12345678-1

# bio
header: ÄGGIE Lee Pak Yee
desc: >
  <a href=" https://beckenkaru.github.io/2020/12/15/upcoming">Upcoming</a> <a href=" https://beckenkaru.github.io/2020/12/12/others">Commissioned</a> <a href=" https://beckenkaru.github.io/archive">Sketch-Archive</a> <a href=" https://beckenkaru.github.io/2020/12/13/print">Prints</a> <a href=" https://beckenkaru.github.io/2020/12/14/animation">Animations</a> <a href=" https://beckenkaru.github.io/2020/12/16/about">About</a>

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
