# site
title: Itchyeggie
baseurl: "/archive"
url: "https://beckenkaru.github.io"
favicon: "/assets/ico.png"
g_analytics: UA-12345678-1

# bio
header: ÄGGIE'S
desc: >
  Upcoming and Commissioned work, sketch archive, prints, and animations. \\
  About her.

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
